name: znn_cli_dart
description: Zenon CLI tool
version: 0.0.7
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  args: ^2.4.2
  dcli: ^4.0.1-beta.4
  znn_sdk_dart:
    git:
      url: https://github.com/drblazer21/znn_sdk_dart.git
      ref: mobile-support
  znn_ledger_dart:
    git:
      url: https://github.com/hypercore-one/znn_ledger_dart.git
      ref: mobile-support
  bip39: ^1.0.6
  convert: ^3.1.1
  collection: ^1.18.0
  path: ^1.9.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.1.1
  dependency_validator: ^3.0.0
  test: ^1.24.4
