name: Build and release znn-cli

on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Flutter action
            uses: subosito/flutter-action@v2.16.0
          - name: Install dependencies
            run: dart pub get
          - name:  Build znn-cli
            run:   |
                   if [ "$RUNNER_OS" == "Linux" ]; then
                        make linux
                   elif [ "$RUNNER_OS" == "Windows" ]; then
                        make windows
                   elif [ "$RUNNER_OS" == "macOS" ]; then
                        make macos
                   else
                        echo "$RUNNER_OS not supported"
                        exit 1
                   fi
            shell: bash
          - name: Upload artifacts
            uses: actions/upload-artifact@v4
            with:
              name: ${{ matrix.os }}-artifacts
              path: ./build/
  make-release:
        needs: [build-matrix]
        runs-on: ubuntu-latest
        steps:
          - name: Prepare environment
            run: |
              sudo apt update
              sudo apt upgrade -y
              sudo apt install -y zip unzip
          - name: Prepare releases directory
            run: mkdir releases
          - name: Download Linux artifacts
            uses: actions/download-artifact@v4
            with:
              name: ubuntu-latest-artifacts
              path: ./znn-cli-linux-amd64
          - name: Download macOS artifacts
            uses: actions/download-artifact@v4
            with:
              name: macos-latest-artifacts
              path: ./znn-cli-macos-arm64
          - name: Download Windows artifacts
            uses: actions/download-artifact@v4
            with:
              name: windows-latest-artifacts
              path: ./znn-cli-windows-amd64
          - name: Package binaries
            run: |
              chmod +x ./znn-cli-linux-amd64/*
              chmod +x ./znn-cli-macos-arm64/*
              zip -r ./znn-cli-windows-amd64.zip ./znn-cli-windows-amd64/*
              zip -r ./znn-cli-linux-amd64.zip ./znn-cli-linux-amd64/*
              zip -r ./znn-cli-macos-arm64.zip ./znn-cli-macos-arm64/*
              mv znn-cli-windows-amd64.zip releases/
              mv znn-cli-linux-amd64.zip releases/
              mv znn-cli-macos-arm64.zip releases/
          - name: Generate checksums
            run: |
              cd releases/
              echo $(sha256sum *)
              echo $(sha256sum *) >> SHA256CHECKSUMS.txt
          - name: Upload files to a GitHub release
            uses: svenstaro/upload-release-action@2.9.0
            with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: releases/*
              tag: ${{ github.ref }}
              file_glob: true
              overwrite: true
              body: ""
